README.md
This option makes it so it can be only built on UNIX environments. If you remove `-o terraform-provider-oneview` but you still keep the `go build`, it will create the binary file in the folder where `go build` was executed, and the binary name will have the same name as the folder and if it requires extension, Go will give it one.
=> Update README.md to remove "-o" option

README.md, docs/r/i3s_plan.html.markdown, oneview/resource_i3s_plan.go
This removes the reqirement to have the deployment network called
deploy.net.   This change depends on the following PR being merged:
https://github.com/HewlettPackard/oneview-golang/pull/102
=> add new attribute deploy_net_name

.travis.yml, Dockerfile, glide.yaml
This PR switches us to using glide to build the plugin and pins on specific versions
of the libraries that we require for the plugin.
We'll also change the Dockerfile build process to use the current source for our
builds vs trying to git clone it from the remote repos.
Signed-off-by: Edward Raigosa <edward.raigosa@hpe.com>
=> Our builds stopped working because latest is no longer working

.travis.yml, README.md, main.go
Hello everyone,
This is an update to the travis build process to test Pull Requests and Branches in the Travis CI pipeline.
The following changes were made:
Let me know your thoughts!
=> Update travis setup

oneview/config.go, oneview/provider.go, oneview/resource_ethernet_network.go, oneview/resource_fc_network.go, oneview/resource_fcoe_network.go, oneview/resource_i3s_plan.go, oneview/resource_icsp_server.go, oneview/resource_logical_interconnect_group.go, oneview/resource_logical_switch_group.go, oneview/resource_network_set.go, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
This PR:
* Removes the need in `config.go` to have a second variable to initialize the first one. This uses a variable that Go runtime can discard quickly once used. Further change to this logic may be required on `oneview-golang` SDK.
* Changes several variables called `error`. This is considered a shadow variable because other developers may want to use the interface `error` (which we can say it's a type, although it's an interface) rather than the variable name later on. Incidences of this thing are small, but it's better not to have a variable named like a built-in package.
* Checks in the config part if the structure is initialized. With no check at all, the app will panic and crash if the method is called. Maybe it's not needed but the configuration already returns an error, so we …
=> Removed shadow variables and unused structures

docs/r/server_profile.html.markdown, oneview/resource_server_profile.go
This...
- Actually sets the `hardware_uri` property, which says it's computed, but was never actually set
- Adds a `hw_filter` property that allows you to filter the HW you choose (when you don't specify a specific blade with `hardware_name`)
=> Support Profile HW Filtering

docs/r/server_profile.html.markdown, oneview/resource_server_profile.go
This allows you to define the power_state of a Profile's HW, so now you can actually turn it on with TF without having to use ICSP
=> Added power_state property to Profile

README.md, docs/r/ethernet_network.html.markdown, oneview/resource_ethernet_network_test.go
This just updates the docs to match the actual code, but it brings up a bigger question/issue: which format (snake_case or camelCase) we want to standardize on for resource properties. It's all over the place right now; for instance, the ethernet network resource uses `vlan_id` but the fcoe resoruce uses `vlanId`. Personally, I'd rather stick with camelCase because the OneView API uses it, so it will be easier to map the properties to the API docs, but I'm not thrilled about changing everything at this point because it'll break people's code if they update :(
=> Updated Eth-Net docs with vlan_id instead of vlanId

docs/r/logical_interconnect_group.html.markdown, oneview/config.go, oneview/resource_logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/auth.go, vendor/github.com/HewlettPackard/oneview-golang/ov/enclosure.go, vendor/github.com/HewlettPackard/oneview-golang/ov/enclosure_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/fc_network.go, vendor/github.com/HewlettPackard/oneview-golang/ov/logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/ov.go, vendor/github.com/HewlettPackard/oneview-golang/ov/server_hardware_type.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage_volume.go, vendor/github.com/HewlettPackard/oneview-golang/rest/method.go, vendor/github.com/HewlettPackard/oneview-golang/rest/netutil.go, vendor/vendor.json
I am not able to create Logical Interconnect Groups with Terraform as described in #47 
I am working to resolve this issue, though it appears there are multiple fields needed to successfully create a LIG.
=> Add Synergy Support for Logical Interconnect Groups

oneview/resource_ethernet_network.go, oneview/resource_ethernet_network_test.go, oneview/resource_fc_network.go, oneview/resource_fc_network_test.go, oneview/resource_fcoe_network.go, oneview/resource_fcoe_network_test.go, oneview/resource_i3s_plan.go, oneview/resource_i3s_plan_test.go, oneview/resource_icsp_server.go, oneview/resource_icsp_server_test.go, oneview/resource_logical_interconnect_group.go, oneview/resource_logical_interconnect_group_test.go, oneview/resource_logical_switch_group.go, oneview/resource_logical_switch_group_test.go, oneview/resource_network_set.go, oneview/resource_network_set_test.go, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, oneview/resource_server_profile_template_test.go, oneview/resource_server_profile_test.go
#53 provided some great tips in implementing import support.  We recently acquired a Synergy system and are evaluating deployments with Ansible and Terraform.
I was able to successfully import:
- oneview_ethernet_network
- oneview_fc_network
- oneview_logical_interconnect_group
- oneview_network_set
These resources ran import ok, but did not put the `name` into the state file which causes some issues:
- oneview_server_profile
- oneview_server_profile_template
I was not able to test importing these resources in my environment:
- icsp_server
- oneview_i3s_plan
- oneview_fcoe_network
- oneview_logical_switch
- oneview_enclosure_group
oneview_enclosure_group seems to be broken in general though based on #46
I don't have a ton of experience with Go or Terraform, so I'm not sure if I put the …
=> Add import support to all resources

docs/r/logical_interconnect_group.html.markdown, oneview/resource_logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/ethernet_network.go, vendor/github.com/HewlettPackard/oneview-golang/ov/logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage_pool.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage_system.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage_volume_attachment.go, vendor/github.com/HewlettPackard/oneview-golang/ov/task.go, vendor/github.com/HewlettPackard/oneview-golang/rest/netutil.go, vendor/vendor.json
This adds a `v3_enabled` option to SNMP Configuration for Logical Interconnect Groups in addition to the existing support for v1/v2.  Additionally fixes up the code for some recent changes made in oneview-golang.
=> Add SNMP v3 configuration support to Logical Interconnect Group

oneview/resource_logical_interconnect_group.go
I've been having problems with Logical Interconnect Groups wanting to change due to the interconnect map entry template order.
For example - 
```
~ module.vci-syncompra01-MiServer-Synergy-eth-ligs-unstacked.oneview_logical_interconnect_group.ligB
interconnect_map_entry_template.0.enclosure_index:        "1" => "2"
interconnect_map_entry_template.0.interconnect_type_name: "Synergy 20Gb Interconnect Link Module" => "Virtual Connect SE 40Gb F8 Module for Synergy"
interconnect_map_entry_template.1.enclosure_index:        "2" => "1"
interconnect_map_entry_template.1.interconnect_type_name: "Virtual Connect SE 40Gb F8 Module for Synergy" => "Synergy 20Gb Interconnect Link Module"
```
Per #53 I changed interconnect_map_entry_template to a TypeSet instead of a TypeList.  I also commented out some …
=> make interconnect_map_entry_template a TypeSet instead of a TypeList

examples/demos/infrastructure_provisioning_with_i3s.tf, oneview/resource_server_profile.go
- Adds power_state attribute to server profile schema which can be used to power-on or off the server hardware.
=> Adding hardware power-on functionality to SP

CHANGELOG.md, README.md, oneview/config.go, oneview/provider.go
=> Api deprecation changes

CHANGELOG.md, examples/server_profile.tf, examples/server_profile_template.tf, oneview/data_source_server_profile.go, oneview/data_source_server_profile_template.go, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go
Fix for Issue 233 and 234 in TF 0.12
#233 #234
=> Issue 233 and Issue 234 Fixed

CHANGELOG.md, data_source.tf, oneview/resource_logical_interconnect_group.go
TF Crashes for Read in LIG due to the bug in LIG Read method while collecting Qos attributes. 
#285
=> LIG Read Issue #285

.github/workflows/CICD.yml, CHANGELOG.md, oneview/data_source_interconnect_type.go, oneview/data_source_logical_interconnect_group.go, oneview/data_source_server_profile.go, oneview/data_source_server_profile_template.go, oneview/data_source_storage_pool.go, oneview/resource_enclosure_group.go, oneview/resource_ethernet_network.go, oneview/resource_fc_network.go, oneview/resource_fcoe_network.go, oneview/resource_hypervisor_cluster_profile.go, oneview/resource_logical_interconnect_group.go, oneview/resource_network_set.go, oneview/resource_server_profile.go, oneview/resource_storage_pool.go, oneview/resource_uplink_set.go
TF Crashes for Read in LIG due to the bug in LIG Read method while collecting Qos attributes.
This Pr is for Terraform-0.11 branch
This PR fixed formatting issues in below files as well :-
oneview/data_source_interconnect_type.go
oneview/data_source_logical_interconnect_group.go
oneview/data_source_server_profile.go
oneview/data_source_server_profile_template.go
oneview/data_source_storage_pool.go
oneview/resource_enclosure_group.go
oneview/resource_ethernet_network.go
oneview/resource_fc_network.go
oneview/resource_fcoe_network.go
oneview/resource_hypervisor_cluster_profile.go
oneview/resource_network_set.go
oneview/resource_server_profile.go
oneview/resource_storage_pool.go
oneview/resource_uplink_set.go
#285
=> LIG Read Issue for Terraform 0.11 #285

CHANGELOG.md, go.mod, go.sum, oneview/resource_server_hardware.go, vendor/github.com/HewlettPackard/oneview-golang/ov/logical_enclosure.go, vendor/github.com/HewlettPackard/oneview-golang/ov/server_hardware.go, vendor/modules.txt
[Use resource from task reponse to query the server hardware instead of using name]
#414
=> Used server hardware uri to get resource and not name

CHANGELOG.md, docs/d/firmware_drivers.html.markdown, examples/firmware_drivers/data_source.tf, go.mod, go.sum, oneview/data_source_firmware_drivers.go, oneview/resource_server_hardware.go, vendor/github.com/HewlettPackard/oneview-golang/ov/firmware_drivers.go, vendor/modules.txt
[Fix for issue 412 to use fw name and version in datasource]
[#412 ]
=> Fix for issue 412 to use fw name and version in datasource

docs/r/server_profile.html.markdown, examples/server_profiles/main.tf, examples/server_profiles/update_resource.tf, go.mod, go.sum, oneview/resource_server_profile.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/modules.txt
This PR adds a list of strings attribute called `force_flag` to the `oneview_server_profile`-resource, that was added in https://github.com/HewlettPackard/oneview-golang/pull/403:
```hcl
data "oneview_server_profile_template" "template" {
name = "${var.product_name}_${var.config_pattern}_${var.firmware_baseline}"
}
resource "oneview_server_profile" "this" {
name                 = var.hostname
hardware_name        = var.hostname
server_hardware_type = data.oneview_server_profile_template.template.server_hardware_type
template             = data.oneview_server_profile_template.template.name
force_flags = ["ignoreServerHealth"]
}
```
I have tested the change and it works as expected:
```bash
data.http.ilo["XXXXXXXX"]: Reading...
data.vault_generic_secret.lxca_creds: Reading... …
```
=> feat(serverprofile): add force param to serverprofile creation

oneview/data_source_server_profile.go, oneview/resource_server_profile.go
Add the MAC address of interfaces to object when creating a new resource and when querying an existing resource.
Resolves issue #552 
I had to use the OV8.6_Validation branch since the master branch at the time was compiling but would fail on apply.
=> Added the output of MAC addresses for interfaces
