.travis.yml, main.go
Signed-off-by: Dian Hansen <dian.hansen@hp.com>
=> add testing

oneview/resource_server_profile.go
Signed-off-by: Matthew Frahry <matthew.frahry@hpe.com>
=> Change blade_bay to frame_bay

oneview/provider.go
Signed-off-by: Matthew Frahry <matthew.frahry@hpe.com>
=> Stop prompt for icsp password

oneview/config.go, oneview/provider_test.go, oneview/resource_ethernet_network.go, oneview/resource_fc_network.go, oneview/resource_fcoe_network.go, oneview/resource_fcoe_network_test.go, oneview/resource_i3s_plan.go, oneview/resource_i3s_plan_test.go, oneview/resource_icsp_server.go, oneview/resource_icsp_server_test.go, oneview/resource_logical_switch_group.go, oneview/resource_logical_switch_group_test.go, oneview/resource_network_set.go, oneview/resource_network_set_test.go, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, oneview/resource_server_profile_template_test.go, oneview/resource_server_profile_test.go
Signed-off-by: Matthew Frahry <matthew.frahry@hpe.com>
=> Fixed fmting and added tests

CONTRIBUTING.md, HACKING.md
Signed-off-by: Bob Fraser <bobfraser1@gmail.com>
=> Update contribution guidelines

endpoints-support.md
Adding endpoints-support.md file to the SDK
=> Endpoint file

endpoints-support.md
Added OS Deployment Plan resource to the endpoint file
- [] New functionality includes testing.
- [] All tests pass for go 1.11.3 + gofmt checks .
- [] New functionality has been documented in the README if applicable.
- [] New functionality has been thoroughly documented in the examples (please include helpful comments).
=> added the missed endpoint deployment plan

CHANGELOG.md, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/connection.go, vendor/github.com/HewlettPackard/oneview-golang/ov/connectionv3.go, vendor/vendor.json
Boot order support for server profile template and server profile
NA
=> Bugfix spt

CHANGELOG.md, examples/demos/infrastructure_provisioning_without_i3s.tf
Use case for infrastructure provisioning.
NA
=> Use case for infrastructure provisioning.

README.md
Updated the Terraform  version in README file.
=> Updated Terraform Version in Readme

oneview/provider.go
Code deleted during the rebase. Readding it.
=> Add storage attachemnt data source to provider file

oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/connection.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage.go, vendor/vendor.json
- Storage profile storage path correction
- [] New functionality has been documented in the README if applicable.
- [] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [] New endpoints supported are updated in the endpoints-support.md file.
- [] Changes are documented in the CHANGELOG.
=> Server profile storage path correction.

examples/server_profile.tf, oneview/resource_server_profile.go
- Gives the fix for the import error on server profile.
- [] New functionality has been documented in the README if applicable.
=> Fix - Import error on server profile

CHANGELOG.md, endpoints-support.md, examples/interconnects.tf
Signed-off-by: root <madhavb@hpe.com>
- Adds Interconnects support for api1000
- [] New functionality has been documented in the README if applicable.
=> Api1000 support for interconnects

oneview/resource_server_profile.go
Updating the lib files for SP resource for bug where the import from SPT was getting overwritten to nill values.
=> SP creation with SPT - Bug fix

.github/pull_request_template.md
Changes to get PR template while we raise PR
NA
=> Changes to get PR template while we raise PR

CHANGELOG.md
=> Release Terrform 1.3

examples/demos/infrastructure_provisioning_with_i3s.tf
Fixed UseCase for SP Creation with Storage Volume
=> Fixed UseCase for SP Creation with Storage Volume

CHANGELOG.md, docs/d/server_profile_template.html.markdown, docs/r/server_profile_template.html.markdown
Wiki Updated for SPT
Issue 29, Updated wiki for SPT in docs
=> wiki_for_SPT

.github/workflows/push_docker.yml, CHANGELOG.md
Automate docker image publish
NA
=> Automate docker image publish

CHANGELOG.md, README.md
=> release PR for v5.4

CHANGELOG.md, oneview/data_source_server_hardware.go
The PR fixes the issue for MP_IP Address value for GET Operation
#118
=> Issue 118 fix

.github/workflows/push_docker.yml, CHANGELOG.md, README.md
=> Release PR

.github/workflows/push_docker.yml
Since set env command is [deprecated](https://github.com/actions/checkout/issues/383) from github, updating the github workflow file. 
=> updated dockerfile

examples/enclosure.tf, examples/enclosure_group.tf, examples/server_hardware.tf, examples/server_hardware_type.tf
Upgraded below resources to terraform v0.12
1. enclosure
2. enclosure_group
3. server_hardware
4. server_hardware_type
=> upgraded enclosure and hardware resources to v0.12

.github/workflows/release.yml, .goreleaser.yml
[Adding files for getting terraform signed for Hashicorp registration]
[]
=> Added release workflow and gorelease file

.github/workflows/push_docker.yml, CHANGELOG.md, README.md, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
Release PR ov5.6 for TF 0.11
N/A
=> TF0.11 Release PR

CHANGELOG.md, examples/server_profile.tf, examples/server_profile_template.tf, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storagev2.go
#267 Fix for false value as Boolean attribute in local storage SPT and SP 
#268 Fixed Local Storage Issue for SP through SPT
#238 Fixed server profile connection settings issue.
#267 
#268 
#238
=> fixed #267

.github/workflows/push_docker.yml, CHANGELOG.md, README.md
=> Release PR for TF 0.11

CHANGELOG.md, examples/server_profile_templates/data_source.tf, oneview/data_source_server_profile_template.go, oneview/resource_server_profile_template.go
fix for Issue 277 for Terraform 0.12
#277
=> fix for Issue 277 for Terraform 0.12

CHANGELOG.md, examples/server_profile_templates/data_source.tf, oneview/data_source_server_profile_template.go, oneview/resource_server_profile_template.go
Fix for Import Configuration for SPT
#277
=> LocalStorage and Connections Import Resource Fixed

CHANGELOG.md, versions.tf
=> Release PR for OV6.1

oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
Fixed Attribute Types
#301 
#300
=> Fix for Issue 301 and 300

go.mod, go.sum, oneview/resource_logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/server_hardware.go, vendor/modules.txt
=> fix for LIG Qos Configuration and PortFlapSettings

examples/server_profiles/main.tf, examples/server_profiles/update_resource.tf, oneview/data_source_server_profile.go
- Add missing sp attributes in dataSource file
- Aligned all the schema attributes in alphabetical order
- updated READ method
=> Add sp attributes in DataSource

docs/d/server_profile_template.html.markdown, go.mod, go.sum, oneview/data_source_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profilesv3.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage.go, vendor/modules.txt
[Added attributes in Datasource]
[]
=> Added attributes in Datasource

docs/d/server_profile_template.html.markdown, docs/r/server_profile_template.html.markdown, oneview/data_source_server_profile_template.go, oneview/resource_server_profile_template.go
updated SPT Connection Settings
=> updated SPT Connection Settings

examples/server_profile_templates/main.tf, oneview/data_source_server_profile_template.go, oneview/resource_server_profile_template.go
- added os deployment settings in spt data source
=> added os deployment settings in spt

CHANGELOG.md, oneview/resource_server_profile_template.go
fixed issue 336, and made few other modifications.
#336
=> Fixed Issue 336

examples/id_pools_ipv4_range/data_source.tf, examples/id_pools_ipv4_range/main.tf, examples/id_pools_ipv4_range/update_resource.tf, examples/id_pools_ipv4_range/update_resource_allocator.tf, examples/id_pools_ipv4_range/update_resource_collector.tf, oneview/data_source_id_pools_ipv4_range.go, oneview/data_source_id_pools_ipv4_range_test.go, oneview/resource_id_pools_ipv4_range.go, oneview/resource_id_pools_ipv4_range_test.go
Support IPv4 Allocator and Collector
=> Support IPv4  Range Allocator and Collector

CHANGELOG.md, oneview/resource_server_profile.go
[Added fix to remove compliance control from SP json request]
[#343 ]
=> Added fix for 343

docs/d/server_profile.html.markdown, docs/d/server_profile_template.html.markdown, docs/r/server_profile.html.markdown, docs/r/server_profile_template.html.markdown, examples/server_profile_templates/main.tf, go.mod, go.sum, oneview/data_source_server_profile.go, oneview/data_source_server_profile_template.go, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profile_templates.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/github.com/HewlettPackard/oneview-golang/utils/helpers.go, vendor/modules.txt
Adding support to MP in SP and SPT
N/A
=> Adding support to MP in SP and SPT

docs/r/server_profile_template.html.markdown, examples/server_profile_templates/main.tf, examples/server_profile_templates/update_resource.tf, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
=> Idempotency check in spt

CHANGELOG.md
Release PR for Terraform 0.11 for OV REST API 3000
=> updatedChangelog for release

oneview/data_source_logical_interconnect_group.go
[Fixed issue 353 by adding set if function to read]
[issue #353 ]
=> Added set id function to read

CHANGELOG.md, examples/server_profiles/main.tf, go.mod, go.sum, oneview/data_source_server_profile.go, oneview/resource_server_profile.go, vendor/github.com/HewlettPackard/oneview-golang/ov/enclosure_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/modules.txt
- Added support to server profile resource on DL servers
=> Implement SP with DL server

CHANGELOG.md, oneview/resource_server_profile_template.go
Added changes for spt idompotency for DL support
#312
=> Added changes for spt idompotency for DL support

CHANGELOG.md, examples/server_hardware/main.tf, go.mod, go.sum, oneview/data_source_server_hardware_type.go, oneview/resource_server_hardware.go, oneview/resource_server_hardware_test.go, vendor/github.com/HewlettPackard/oneview-golang/ov/server_hardware.go, vendor/github.com/HewlettPackard/oneview-golang/ov/server_hardware_type.go, vendor/modules.txt
=> Support Delete for DL

examples/server_profiles/main.tf, oneview/resource_server_hardware.go, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
Idempotency check on SP/SPT for DL
=> Idempotency check on SP/SPT for DL

CHANGELOG.md, go.mod, go.sum, oneview/resource_logical_enclosure.go, oneview/resource_server_profile.go, vendor/github.com/HewlettPackard/oneview-golang/ov/logical_enclosure.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/modules.txt
[Added server profile description and intial scope uris in le]
[#369 ]
=> Added server profile description and intial scope uris in le

CHANGELOG.md, docs/r/logical_interconnect_group.html.markdown, oneview/data_source_logical_interconnect_group.go, oneview/resource_logical_interconnect_group.go
Added attribute to support DesiredFecMode in LIG
#371
=> DesiredFecMode for LIG

CHANGELOG.md, docs/d/server_profile.html.markdown, docs/r/logical_interconnect_group.html.markdown, docs/r/server_profile.html.markdown, examples/server_profile_templates/main.tf, examples/server_profiles/main.tf, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
In this PR we shall complete the idempotency for below attributes. 
#295 
#370 
NA
=> SP Idempotency

CHANGELOG.md, go.mod, go.sum, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profile_templates.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/modules.txt
Support hostname in SP/SPT iLOSettings
Fixes #360
=> Support hostname in SP/SPT iLOSettings

docs/r/server_profile.html.markdown, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
Update firmware attributes for SP/SPT
=> Update firmware attributes for SP/SPT

docs/d/connection_templates.html.markdown, docs/r/connection_templates.html.markdown, examples/connection_templates/data_source.tf, go.mod, go.sum, oneview/data_source_connection_templates.go, oneview/resource_connection_templates.go, vendor/github.com/HewlettPackard/oneview-golang/ov/connection_templates.go, vendor/modules.txt
added connection settings to get by Uri
NA
=> added connection settings to get by Uri

CHANGELOG.md, examples/server_hardware/main.tf, oneview/resource_server_hardware.go
=> Issue 387 fix

oneview/resource_server_profile.go
fix for bios option in SP Read
#390
=> fix for bios option in SP Read

examples/connection_templates/main.tf
updated example for connection template
=> updated example for connection template

docs/d/ethernet_network.html.markdown, docs/r/ethernet_network.html.markdown, examples/ethernet_networks/main.tf, oneview/data_source_ethernet_network.go, oneview/resource_ethernet_network.go
Enhancement for ethernet network to update bandwidth while creating ethernet network 
n/a
=> updated ethernet network to update connection template

docs/d/fc_network.html.markdown, docs/d/fcoe_network.html.markdown, docs/r/fc_network.html.markdown, docs/r/fcoe_network.html.markdown, examples/fc_networks/main.tf, examples/fcoe_networks/main.tf, oneview/data_source_fc_network.go, oneview/data_source_fcoe_network.go, oneview/resource_fc_network.go, oneview/resource_fcoe_network.go
added connection template in FC and FCOE Networks
=> added connection template in FC and FCOE Networks

.github/workflows/push_docker.yml
=> Update docker version

CHANGELOG.md, README.md, versions.tf
[Describe what this change achieves]
[Release 6.3.1-13]
=> release 6.3.1-13

oneview/resource_server_profile_template.go
Idempotency check for boot order
=> Idempotency check for SPT boot

CHANGELOG.md, oneview/resource_server_profile_template.go
Idempotency check for SPT Local Storage
=> Idempotency check for SPT Local Storage

CHANGELOG.md, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
[Describe what this change achieves]
[#453 ]
=> Fixed ilo read error

go.mod, go.sum, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profile_templates.go, vendor/modules.txt
=> added spt ilo changes

CHANGELOG.md, oneview/resource_labels.go
=> fixed issue 451

examples/server_profiles/main.tf
[Added sp creation from spt example]
=> Added sp creation from spt example

go.mod, go.sum, vendor/github.com/HewlettPackard/oneview-golang/ov/firmware_drivers.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage_volume_template.go, vendor/modules.txt
[fw driver fix for issue 463]
[#463 ]
=> fw driver fix for issue 463

CHANGELOG.md, examples/server_profile_templates/main.tf, go.mod, go.sum, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage.go, vendor/modules.txt
[Issue 474-Create SPT with SAN storage ]
[#474 ]
=> Issue 474-Create SPT with SAN storage 

CHANGELOG.md, oneview/resource_server_profile_template.go
[Fix  SPT import crash by adding nil check for mp settings]
[#468 ]
=> Fix  SPT import crash by adding nil check for mp settings

CHANGELOG.md, oneview/resource_fc_network.go
[Allow managed san uri while fc network creation]
=> fix for issue471 from terraform

CHANGELOG.md, oneview/resource_server_profile.go, oneview/resource_server_profile_template.go
[fix for issue462 from terraforms]
[#462 ]
=> fix for issue462 from terraform

CHANGELOG.md, go.mod, go.sum, oneview/resource_logical_interconnect_group.go, oneview/resource_server_profile.go, vendor/github.com/HewlettPackard/oneview-golang/ov/logical_interconnect_group.go, vendor/github.com/HewlettPackard/oneview-golang/ov/storage_volume.go, vendor/modules.txt
[Fixed the update function of LIG so that SNMP, Switch Map, interconnect settings,and internal networks are does not get modified unnecessarily during LIG Update.]
[#467 ]
=> Update uplink set intial commit

CHANGELOG.md, docs/d/relative_value.html.markdown, examples/logical_interconnect_groups/main.tf, oneview/data_source_relatve_value.go, oneview/provider.go
[Getting relative value from portanem using datasource]
=> Portname relative value

.github/workflows/push_docker.yml, CHANGELOG.md, README.md, endpoints-support.md, go.mod, go.sum, vendor/github.com/HewlettPackard/oneview-golang/ov/config.go, vendor/github.com/HewlettPackard/oneview-golang/ov/profiles.go, vendor/modules.txt, versions.tf
=> OV 8.0 validation

docs/r/server_profile_template.html.markdown
The markdown syntax for code blocks was wrong. I fixed it.
=> fixed: hcl highlighting

CHANGELOG.md, oneview/resource_logical_interconnect_group.go
=> fix the issue #507

.github/workflows/push_docker.yml, CHANGELOG.md, README.md, endpoints-support.md, versions.tf
=> OV8.1 validation

CHANGELOG.md, oneview/resource_logical_interconnect_group.go
[Fixed lig enable fact mac cache failover]
[ #517  ]
=> Fixed lig enable fact mac cache failover

.github/workflows/release.yml, .goreleaser.yml, CHANGELOG.md
[Darwin arm64 support]
[#518 ]
=> Darwin arm64 support

CHANGELOG.md, README.md
[Fixed broken links in README]
[#529 ]
=> Fixed broken links in README

CHANGELOG.md, docs/d/firmware_drivers.html.markdown, examples/firmware_drivers/data_source.tf, examples/firmware_drivers/main.tf, oneview/data_source_firmware_drivers.go, vendor/github.com/HewlettPackard/oneview-golang/ov/firmware_drivers.go
[Fixed firmware datasource bug]
[#523 #524 ]
=> Fixed firmware datasource bug

CHANGELOG.md, oneview/resource_logical_interconnect_group.go
[Type change for enable network loop protection enabled]
=> Type change for enable network loop protection enabled

examples/server_profiles/update_resource.tf
[Describe what this change achieves]
=> modified update resource for server profile

examples/server_profiles/update_resource.tf
[Describe what this change achieves]
=> Updated server profile update_resource.tf
